spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/Konrad_Digital_Document
        username: postgres
        password: 12345
        
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
        
    application:
        name: konrad
    jackson:
        serialization:
            fail-on-empty-beans: false
            
info.name: konrad

server:
    port: 9090